### DISCUSSION TITLE
How to skip release date in version title?

### DISCUSSION THREAD

**Discussion by perspilling** [stefanzweifel/changelog-updater-action#24] [Q&A]
I would like to not have a generated date in the version title as the date is already part of our release tag, i.e. our release tags look like this: `v22.10.18-build997.170f99f91` 

We also have some cases where the tag might have been added after the commit that triggered the build (this is a temporary issue as the tag is now added automatically with every build, but it wasn't in earlier releases). If we have such a tag that was added after the commit that triggered the build we get a version title in the changelog that might look like this: 
```
## v22.10.18-build997.170f99f91 - 2022-10-21
```

Is it possible to avoid that date in the title?

**Comment by perspilling** [comment]
Btw. I also tried to set the release-date like this:
```
      - name: Extract release date from TO_TAG
        id: release_date
        run: |
          echo "RELEASE_DATE=$(echo ${{ env.TO_TAG }} | awk -F  '[v-]' '{print $2}')" >>  $GITHUB_ENV

      - name: Update CHANGELOG
        uses: stefanzweifel/changelog-updater-action@v1.6.0
        with:
          release-date: ${{ env.RELEASE_DATE }}
```
..but that had no effect, i.e. it didn't use the date (22.10.18) I supplied.

**Reply by stefanzweifel** [reply]
That sounds like a bug, if `env.RELEASE_DATE` really contained `22.10.18`. I think the CLI behind the Action doesn't do any date validation and would allow a date in the format of `y.m.d`.

**Reply by perspilling** [reply]
Well, it doesn't work in my case. I.e. if I have the following steps:
```
      - name: Extract release date from TO_TAG
        id: release_date
        run: |
          echo "RELEASE_DATE=$(echo ${{ env.TO_TAG }} | awk -F  '[v-]' '{print $2}')" >>  $GITHUB_ENV

      - name: Print RELEASE_DATE
        run: echo RELEASE_DATE=${{ env.RELEASE_DATE }}

      - name: Update CHANGELOG
        uses: stefanzweifel/changelog-updater-action@v1.6.0
        with:
          release-date: ${{ env.RELEASE_DATE }}
          latest-version: ${{ steps.build_changelog.outputs.toTag }}
          path-to-changelog: ${{ env.CHANGELOG_FILE }}
          release-notes: ${{ steps.build_changelog.outputs.changelog }}
```
..I get the following result:
```
[Update Changelog/Update Changelog] ⭐ Run Main Print RELEASE_DATE
[Update Changelog/Update Changelog]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/9] user= workdir=
| RELEASE_DATE=22.10.20
...
| # Changelog for unreleased changes
| 
| ## v22.10.20-build999.724652eed - 2022-10-24
```
Can you make a test with the release-date to to this format `22.10.20`?

**Reply by stefanzweifel** [reply]
@perspilling Will do a test this evening.

Meanwhile, can you try this?

```diff
      - name: Extract release date from TO_TAG
        id: release_date
        run: |
-         echo "RELEASE_DATE=$(echo ${{ env.TO_TAG }} | awk -F  '[v-]' '{print $2}')" >>  $GITHUB_ENV
+         echo "RELEASE_DATE=$(echo ${{ env.TO_TAG }} | awk -F  '[v-]' '{print $2}')" >>  $GITHUB_OUTPUT

-     - name: Print RELEASE_DATE
-       run: echo RELEASE_DATE=${{ env.RELEASE_DATE }}

      - name: Update CHANGELOG
        uses: stefanzweifel/changelog-updater-action@v1.6.0
        with:
-         release-date: ${{ env.RELEASE_DATE }}
+         release-date: ${{ steps.release_date.RELEASE_DATE }}
          latest-version: ${{ steps.build_changelog.outputs.toTag }}
          path-to-changelog: ${{ env.CHANGELOG_FILE }}
          release-notes: ${{ steps.build_changelog.outputs.changelog }}
```

Instead of writing to the GitHub Environment the workflow creates an output paramter. 
That could then be consumed again in by `stefanzweifel/changelog-updater-action` by referencing the ID and the name of the parameter (`steps.release_date.RELEASE_DATE`).

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

I previously never changed the GitHub Environment in an Action workflow before. I thought there is a difference between how to access variables between steps that run something in a UNIX shell (eg. `run: echo ${{ env.RELEASE_DATE }}`) and when referencing a variable when passing it as an input to an action.

But it could well be that I'm in the wrong here. This part of Actions is not well documented; and seems to change every 3 months.

**Reply by stefanzweifel** [reply]
Just added a test to the underlying CLI to confirm that `release-date` can be anything. The CLI doesn't do any date-formatting.

- Commit: https://github.com/stefanzweifel/php-changelog-updater/commit/8c0aae87bae1a512bdc1a33a413469e7d1d8c9c4#diff-e4714ca0100283ebb51d7224e0829d0e7486eea1b39890e41eb561693087b1f4R359
- Automated Test Run: https://github.com/stefanzweifel/php-changelog-updater/actions/runs/3314664751/jobs/5474244145#step:6:53

**Reply by perspilling** [reply]
Ok, thx. I will make the changes you suggest.

**Reply by perspilling** [reply]
I'm getting this error message when I do that: `$GITHUB_OUTPUT: ambiguous redirect` Do you know how to fix that?

**Reply by perspilling** [reply]
Hmm, maybe it is a problem with the nektos/act version that I'm using to test this locally...

**Reply by perspilling** [reply]
Yes, indeed: https://github.com/nektos/act/issues/1386

**Reply by perspilling** [reply]
I will use `set-output` for now then

**Reply by perspilling** [reply]
This works in act:
```
      - name: Extract release date from TO_TAG
        id: release_date
#        run: echo "releaseDate=$(echo ${{ env.TO_TAG }} | awk -F  '[v-]' '{print $2}')" >>  $GITHUB_OUTPUT # not supported by act yet
        run: echo ::set-output name=releaseDate::$(echo ${{ env.TO_TAG }} | awk -F  '[v-]' '{print $2}')

      - name: Update CHANGELOG
        uses: stefanzweifel/changelog-updater-action@v1.6.0
        with:
          release-date: ${{ steps.release_date.outputs.releaseDate }}
```
and then the release date is indeed set to the yy.mm.dd date given in the version tag :-)
