### DISCUSSION TITLE
I labelled my release as "pre-release" and the action didn't run.

### DISCUSSION THREAD

**Discussion by danielh-official** [stefanzweifel/changelog-updater-action#47] [Q&A] [answered]
Does it only run when the release is not labelled "pre-release"?

**Comment by stefanzweifel** [comment, marked as answer]
Hey @danielh-official,

I guess your workflow looks like this?

```yml
name: "Update Changelog"

on:
  release:
    types: [released]
```

If yes, the workflow is only run for released released. If the workflow should run in both cases, you can add the `prereleased`-activity type.

```yml
name: "Update Changelog"

on:
  release:
    types: [released, prereleased]
```

See the GitHub Action trigger docs for details: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release
