### ISSUE TITLE
Add output providing compare-releases URL 

### ISSUE THREAD

**Issue by HannesWell** [stefanzweifel/changelog-updater-action#14]
It would be handy if this action would provide an output variable that contains the URL to compare the recent with the previous release, which is also added to an release-entry and looks similar to the following:
`https://github.com/org/repo/compare/v1.0.0...v1.1.0`

For example this URL could be added to a automatically created GH-Release.

**Comment by stefanzweifel** [comment]
Thanks for sharing our idea. Quick question: 

> For example this URL could be added to a automatically created GH-Release.

I don't understand that use case. Mabye you can explain this a bit more?

The Action can currently only be used when listening on the `release`-trigger. Meaning that a new release on GitHub has already been created. If I understood correctly, your workflow would look like this:

```mermaid
  graph TD;
      A[Create GitHub Release] --> B[Run changelog-updater Action];
      B --> C[Update Changelog]
      B --> D[Extract compare-release URL];
      D --> E[Update just created GitHub Release];
```

Or would you like to run the Action in a Workflow that doesn't listen to the `release`-trigger?

---

A compare URL could also be generated on the fly in the GitHub UI by clicking on the compare dropdown next to a release; but I can see that you would like to automate that step.

<img width="534" alt="Screenshot 2022-03-12 at 18 24 53" src="https://user-images.githubusercontent.com/1080923/158028167-873db17b-12e9-4e77-a542-2ebe3fe01668.png">

---

The biggest hurdle to implement something like this, is that this Action is very dumb and all the logic lives inside the PHP CLI. Maybe there is an easy way to expose such variables to GitHub Actions from inside the CLI. Have to do some research.

**Comment by HannesWell** [comment]
> Thanks for sharing our idea. Quick question:
> 
> > For example this URL could be added to a automatically created GH-Release.
> 
> I don't understand that use case. Mabye you can explain this a bit more?

> Or would you like to run the Action in a Workflow that doesn't listen to the `release`-trigger?

Exactly I would like to use this action in a manually release-workflow (so it listens to the `workflow_dispatch`-event) that performs all release steps release a Java project build with Maven to Maven-Central and also updates the changelog and creates a corresponding GH release. So it is the other way round: The GH-release is created by the workflow. The goal was to have a one-click release process and to craft the changelog manually during development (as I have described in #12).

I have set up the following (Java/Maven)workflow that does these step already:
https://github.com/axkr/symja_android_library/blob/fa244dc88651caaf90bc5f7f9a37a6658609c213/.github/workflows/maven-perform-release.yml#L46

I created it with your action and the associated [keepachangelog](https://keepachangelog.com/en/1.0.0/) in mind but suited to my workflow. At the moment that workflow is a bit complicated/low-level and only works for a fixed `## [Unreleased]` without subsequent link and does not yet create the compare URL. But it can be achieved when querying the git for the latest tag before creating the commits for the next release.
However I would like to streamline/simplify this workflow (and thought that others could benefit from it) which is why I suggested these changes.

> 
> The biggest hurdle to implement something like this, is that this Action is very dumb and all the logic lives inside the PHP CLI. Maybe there is an easy way to expose such variables to GitHub Actions from inside the CLI. Have to do some research.

I think what can help here are workflow-commands:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions

As far as I understand it you can set the output by just echoing a string like: '::set-output name=SELECTED_COLOR::green'

**Comment by stefanzweifel** [comment]
Quick update on this: I've prepared a PR in the underlying CLI to support GitHub Actions output. See https://github.com/stefanzweifel/php-changelog-updater/pull/18.

The PR includes a `RELEASE_COMPARE_URL` (the thing you want) and a `UNRELEASED_COMPARE_URL` output.

Haven't tested this yet in the GitHub Action itself. Will probably merge the PR once the tests are complete.

**Comment by stefanzweifel** [comment]
The pull request has been merged and the Action now supports this feature since [`v1.4.0`](https://github.com/stefanzweifel/changelog-updater-action/releases/tag/v1.4.0).

Here is an example portion of a workflow to explain how this works:

```yaml
- name: Update Changelog
  uses: stefanzweifel/changelog-updater-action@v1
  id: "changelog-updater"
  with:
    # Pass extracted release date, release notes and version to the Action.
    release-date: ${{ steps.release_date.outputs.date }}
    release-notes: ${{ github.event.release.body }}
    latest-version: ${{ github.event.release.tag_name }}
    compare-url-target-revision: ${{ github.event.release.target_commitish }}

- name: "release_compare_url"
  # https://github.com/org/repo/compare/v1.0.0...v1.1.0
  run: "echo ${{ steps.changelog-updater.outputs.release_compare_url }}"

- name: "unreleased_compare_url"
  # https://github.com/org/repo/compare/v1.0.0...HEAD
  run: "echo ${{ steps.changelog-updater.outputs.unreleased_compare_url }}"
```

If you've been using `v1` of the Action, there is nothing to upgrade … besides your workflow script.
