### ISSUE TITLE
Docs: Add needed permissions in case of an unpriviliged workflow/token

### ISSUE THREAD

**Issue by stevenengland** [stefanzweifel/changelog-updater-action#29]
Hi,

if a repo uses a resticted access it is neccessary to explicitely add permissions to use this action. Reading the code I guess in your case it is:

```
jobs:
  update_changelog:
    permissions:
      contents: write # <-- This one
```

I'll try it out as soon as I can. But can you confirm that?
