### ISSUE TITLE
RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator()

### ISSUE THREAD

**Issue by jeremy379** [stefanzweifel/changelog-updater-action#5]
Hello

First, thank you for this package.

I'm currently trying to implement it but I facing an issue with my GitHub action while running the update changelog step

Here is the error I got

```
Deprecated: Return type of HumbugBox3130\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///changelog-updater/.box/src/RequirementCollection.php on line 12

Deprecated: Return type of HumbugBox3130\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///changelog-updater/.box/src/RequirementCollection.php on line 16

In Assert.php line 2060:
                                             
  No latest-version option provided. Abort.  
```

Here is the update-changelog.yml file used for the action

```
# .github/workflows/update-changelog.yaml
name: "Update Changelog"

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1.1.1
        with:
          release-notes: ${{ github.event.release.body }}
          latest-version: ${{ github.event.release.name }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

```

Seeing that the error could be related to PHP 8.1, I tried to force PHP to run on version 8 but without success (Piece of code added between Checkout code & Update changelog step)

```
- name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: "8.0"
```

Could you help me figure out what happen?

Thank you
